# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\___科创作业-评价系统测试\UIs\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1102, 647)
        MainWindow.setStyleSheet("QPushButton{\n"
                                 "background-color:\n"
                                 "qlineargradient(spread:pad,x1:0,x2:0, y1:0, y2:1,\n"
                                 "stop: 0 rgba(130,130,130,255),\n"
                                 "stop: 0.495 rgba(0,0,0,255),\n"
                                 "stop: 0.505 rgba(0,0,0,255),\n"
                                 "stop: 1 rgba(130,130,130,255));\n"
                                 " \n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border: none;\n"
                                 "border-radius: 5px;\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "font: 75 12pt \"微软雅黑\";\n"
                                 "}\n"
                                 " \n"
                                 "QPushButton:hover{\n"
                                 "background-color:\n"
                                 "qlineargradient(spread:pad,x1:0,x2:0, y1:0, y2:3,\n"
                                 "stop: 0 rgba(150,150,150,230),\n"
                                 "stop: 0.495 rgba(0,0,0,230),\n"
                                 "stop: 0.505 rgba(0,0,0,230),\n"
                                 "stop: 1 rgba(150,150,150,230));\n"
                                 " \n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border: none;\n"
                                 "border-radius: 10px;\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "font: 75 12pt \"微软雅黑\";\n"
                                 "}\n"
                                 " \n"
                                 "QPushButton:pressed{\n"
                                 "background-color:\n"
                                 "qlineargradient(spread:pad,x1:0,x2:0, y1:0, y2:1,\n"
                                 "stop: 0 rgba(100,100,100,255),\n"
                                 "stop: 0.495 rgba(0,0,0,255),\n"
                                 "stop: 0.505 rgba(0,0,0,255),\n"
                                 "stop: 1 rgba(100,100,100,255));\n"
                                 " \n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border: none;\n"
                                 "border-radius: 5px;\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "font: 75 12pt \"微软雅黑\";\n"
                                 "padding-left:2px;\n"
                                 "padding-top:1px;\n"
                                 "}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1102, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LQ"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "查找"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
